[project]
name = "python_template_repo"
version = "0.1.0"
description = "A Python template repository."
readme = "README.md"
requires-python = ">=3.11"
dynamic = ['version']
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "uvicorn>=0.22.0,<0.23.0",
]

[project.optional-dependencies]
dev = ["ruff>=0.0.289,<0.0.290", "pyright>=1.1.320,<1.1.321"]

[tool.uv]
default-groups = []
prerelease = "if-necessary-or-explicit"

[tool.ruff]
select = ["E", "F", "W", "C", "N", "Q", "B", "I"]
ignore = []
line-length = 88
extend-select = ["ANN", "ARG", "D", "PIE", "PT", "RET", "S", "TCH", "UP"]
fix = true


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pep8-naming]
ignore-names = ["X*"]

[tool.pyright]
typeCeckingMode = "standard"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
