"""Reviewer agent models and fail-soft informational flag helpers."""

# ruff: noqa: Q000

import json
import re

from langchain_core.messages import AIMessage
from pydantic import BaseModel, Field
from pydantic_ai import Agent, RunContext
from pydantic_ai.models.openai import Model, ModelSettings

from statmate.agents.summarizer_agent import Finding

_DIAGNOSTIC_TEST_TOKENS = (
    "anderson",
    "assumption",
    "bartlett",
    "cramer",
    "dagostino",
    "jarque",
    "kolmogorov",
    "levene",
    "lilliefors",
    "normality",
    "shapiro",
)


class ReviewerEvidence(BaseModel):
    """Structured raw-result metadata exposed to the reviewer."""

    test_name: str = Field(description="Name of the performed statistical test.")
    effect_size_type: str | None = Field(default=None, description="Effect size label for the test, if available.")
    confidence_interval: list[float] | None = Field(
        default=None,
        description="Confidence interval for the test, if available.",
    )
    p_value: float | None = Field(default=None, description="Observed p-value for the test, if available.")


class ReviewerInformationalFlags(BaseModel):
    """Non-blocking reviewer advisories computed from structured inputs."""

    missing_structure_flags: list[str] = Field(
        default_factory=list,
        description="Tests missing a corresponding structured finding entry.",
    )
    missing_effect_size_flags: list[str] = Field(
        default_factory=list,
        description="Tests missing an effect size label.",
    )
    missing_ci_flags: list[str] = Field(
        default_factory=list,
        description="Tests missing a confidence interval where one is expected.",
    )
    multiplicity_warning: str | None = Field(
        default=None,
        description="Informational warning for multiple comparisons.",
    )


class ReviewerDeps(BaseModel):
    """Inputs required by the reviewer agent."""

    summary: str = Field(description="Summary generated by the summariser node.")
    results: list[AIMessage] = Field(description="Raw AIMessage outputs from each statistical test.")
    probabilities: dict[str, float] = Field(description="P-values keyed by test name.")
    performed_tests: list[str] = Field(
        default_factory=list,
        description="Ordered list of tests explicitly performed in the analysis.",
    )
    findings: list[Finding] = Field(
        default_factory=list,
        description="Structured findings emitted by the summarizer.",
    )
    result_context: list[ReviewerEvidence] = Field(
        default_factory=list,
        description="Structured raw-result metadata used for fail-soft validation.",
    )


class ReviewerResult(BaseModel):
    """Reviewer verdict with optional adjustments."""

    approved: bool = Field(description="True if the narrative matches the statistical evidence.")
    adjusted_summary: str = Field(description="Final vetted summary (may be same as input).")
    hallucination_flags: list[str] = Field(description="Specific issues or hallucinations detected.")
    risk_score: float = Field(description="0-1 confidence score; higher means higher risk of hallucination.")
    notes: str = Field(description="Supporting rationale or caveats.")
    missing_structure_flags: list[str] = Field(
        default_factory=list,
        description="Performed tests missing a structured finding entry.",
    )
    missing_effect_size_flags: list[str] = Field(
        default_factory=list,
        description="Tests missing an effect size label.",
    )
    missing_ci_flags: list[str] = Field(
        default_factory=list,
        description="Tests missing a confidence interval where one is expected.",
    )
    multiplicity_warning: str | None = Field(
        default=None,
        description="Informational warning for multiple comparisons.",
    )

    def __str__(self) -> str:  # pragma: no cover - formatting helper
        """Render the reviewer verdict for log-style display."""
        status = "APPROVED" if self.approved else "FLAGGED"
        flags = "; ".join(self.hallucination_flags) if self.hallucination_flags else "None"
        advisory_lines = [
            f"Missing Structure Flags: {self.missing_structure_flags or []}",
            f"Missing Effect Size Flags: {self.missing_effect_size_flags or []}",
            f"Missing CI Flags: {self.missing_ci_flags or []}",
        ]
        if self.multiplicity_warning:
            advisory_lines.append(f"Multiplicity Warning: {self.multiplicity_warning}")
        return (
            f"Reviewer Status: {status}\n"
            f"Adjusted Summary: {self.adjusted_summary}\n"
            f"Flags: {flags}\n"
            f"Risk Score: {self.risk_score:.2f}\n"
            f"Notes: {self.notes}\n" + "\n".join(advisory_lines)
        )


def collect_reviewer_informational_flags(deps: ReviewerDeps) -> ReviewerInformationalFlags:
    """Derive non-blocking medical-reporting flags from reviewer inputs."""
    reportable_tests = _collect_reportable_test_names(deps)
    reportable_probabilities = _collect_reportable_probabilities(deps)
    missing_structure_flags = [
        test_name
        for test_name in reportable_tests
        if not any(_finding_mentions_test(finding, test_name) for finding in deps.findings)
    ]
    missing_effect_size_flags = [
        evidence.test_name
        for evidence in deps.result_context
        if not _is_diagnostic_test_name(evidence.test_name) and not evidence.effect_size_type
    ]
    missing_ci_flags = [
        evidence.test_name
        for evidence in deps.result_context
        if not _is_diagnostic_test_name(evidence.test_name)
        and _confidence_interval_required(evidence.test_name)
        and not _has_confidence_interval(evidence.confidence_interval)
    ]
    return ReviewerInformationalFlags(
        missing_structure_flags=_deduplicate(missing_structure_flags),
        missing_effect_size_flags=_deduplicate(missing_effect_size_flags),
        missing_ci_flags=_deduplicate(missing_ci_flags),
        multiplicity_warning=_build_multiplicity_warning(reportable_probabilities),
    )


def apply_reviewer_informational_flags(result: ReviewerResult, deps: ReviewerDeps) -> ReviewerResult:
    """Merge deterministic fail-soft reviewer advisories into the agent verdict."""
    informational_flags = collect_reviewer_informational_flags(deps)
    has_info_only_flags = any(
        [
            bool(informational_flags.missing_structure_flags),
            bool(informational_flags.missing_effect_size_flags),
            bool(informational_flags.missing_ci_flags),
            informational_flags.multiplicity_warning is not None,
        ]
    )
    approved = result.approved
    if (
        has_info_only_flags
        and not result.approved
        and not result.hallucination_flags
        and not _summary_was_adjusted(result.adjusted_summary, deps.summary)
        and result.risk_score <= 0.25
        and not _notes_indicate_substantive_rejection(result.notes)
    ):
        approved = True
    return result.model_copy(
        update={
            "approved": approved,
            "missing_structure_flags": informational_flags.missing_structure_flags,
            "missing_effect_size_flags": informational_flags.missing_effect_size_flags,
            "missing_ci_flags": informational_flags.missing_ci_flags,
            "multiplicity_warning": informational_flags.multiplicity_warning,
        }
    )


def _deduplicate(values: list[str]) -> list[str]:
    seen: set[str] = set()
    deduped: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped


def _summary_was_adjusted(adjusted_summary: str, original_summary: str) -> bool:
    return _normalize_summary_text(adjusted_summary) != _normalize_summary_text(
        _extract_primary_summary(original_summary)
    )


def _extract_primary_summary(summary: str) -> str:
    marker = "Summary:"
    if marker not in summary:
        return summary.strip()
    summary_body = summary.split(marker, 1)[1].strip()
    section_markers = (
        "\n\nRecommendations:",
        "\nRecommendations:",
        "\n\nPerformed Tests:",
        "\nPerformed Tests:",
        "\n\nFindings:",
        "\nFindings:",
        "\n\nPower Interpretation:",
        "\nPower Interpretation:",
    )
    for section_marker in section_markers:
        if section_marker in summary_body:
            return summary_body.split(section_marker, 1)[0].strip()
    return summary_body


def _normalize_summary_text(value: str) -> str:
    return " ".join(value.split()).casefold()


def _notes_indicate_substantive_rejection(notes: str) -> bool:
    normalized_notes = _normalize_summary_text(notes)
    non_substantive_tokens = (
        "faithful to the evidence",
        "grounded in the provided evidence",
        "grounded in the evidence",
        "no unsupported claims",
    )
    if any(token in normalized_notes for token in non_substantive_tokens):
        return False
    substantive_tokens = (
        "cannot verify",
        "hallucination",
        "insufficient evidence",
        "mismatch",
        "not grounded",
        "not supported",
        "overstates",
        "reject",
        "unsupported",
        "unverified",
    )
    if any(token in normalized_notes for token in substantive_tokens):
        return True
    return _notes_describe_evidence_claim_mismatch(normalized_notes)


def _notes_describe_evidence_claim_mismatch(normalized_notes: str) -> bool:
    note_tokens = set(re.findall(r"[a-z0-9']+", normalized_notes))
    claim_subject_tokens = {
        "claim",
        "claims",
        "conclusion",
        "conclusions",
        "finding",
        "findings",
        "narrative",
        "report",
        "reported",
        "summary",
    }
    evidence_subject_tokens = {
        "data",
        "evidence",
        "result",
        "results",
    }
    mismatch_phrases = (
        "does not support",
        "do not support",
        "did not support",
        "fails to support",
        "fail to support",
        "is not supported",
        "are not supported",
        "does not match",
        "do not match",
        "did not match",
        "not grounded in",
    )
    return (
        bool(claim_subject_tokens & note_tokens)
        and bool(evidence_subject_tokens & note_tokens)
        and any(phrase in normalized_notes for phrase in mismatch_phrases)
    )


def _normalize_test_label(value: str) -> str:
    return value.lower().replace("_", " ").replace("-", " ")


def _is_diagnostic_test_name(test_name: str) -> bool:
    normalized_test_name = _normalize_test_label(test_name)
    return any(token in normalized_test_name for token in _DIAGNOSTIC_TEST_TOKENS)


def _collect_reportable_test_names(deps: ReviewerDeps) -> list[str]:
    reportable_tests = [test_name for test_name in deps.performed_tests if not _is_diagnostic_test_name(test_name)]
    reportable_tests.extend(
        evidence.test_name for evidence in deps.result_context if not _is_diagnostic_test_name(evidence.test_name)
    )
    if reportable_tests:
        return _deduplicate(reportable_tests)
    return [test_name for test_name in deps.probabilities if not _is_diagnostic_test_name(test_name)]


def _collect_reportable_probabilities(deps: ReviewerDeps) -> dict[str, float]:
    reportable_probabilities = {
        test_name: deps.probabilities[test_name]
        for test_name in _collect_reportable_test_names(deps)
        if test_name in deps.probabilities
    }
    if reportable_probabilities:
        return reportable_probabilities
    return {
        test_name: p_value
        for test_name, p_value in deps.probabilities.items()
        if not _is_diagnostic_test_name(test_name)
    }


def _finding_mentions_test(finding: Finding, test_name: str) -> bool:
    haystack = " ".join(part for part in [finding.finding, finding.evidence, finding.caveat or ""] if part)
    normalized_haystack = _normalize_test_label(haystack)
    normalized_test = _normalize_test_label(test_name)
    if normalized_test in normalized_haystack:
        return True
    tokens = [token for token in normalized_test.split() if token not in {"test"}]
    return bool(tokens) and all(token in normalized_haystack for token in tokens)


def _has_confidence_interval(confidence_interval: list[float] | None) -> bool:
    return confidence_interval is not None and len(confidence_interval) == 2


def _confidence_interval_required(test_name: str) -> bool:
    normalized_test = _normalize_test_label(test_name)
    required_tokens = (
        "t test",
        "ttest",
        "welch",
        "mann whitney",
        "pearson",
        "spearman",
        "correlation",
    )
    return any(token in normalized_test for token in required_tokens)


def _build_multiplicity_warning(probabilities: dict[str, float]) -> str | None:
    comparison_count = len(probabilities)
    if comparison_count <= 1:
        return None
    adjusted_alpha = 0.05 / comparison_count
    surviving = [test_name for test_name, p_value in probabilities.items() if p_value <= adjusted_alpha]
    not_surviving = [test_name for test_name, p_value in probabilities.items() if p_value > adjusted_alpha]
    surviving_text = ", ".join(surviving) if surviving else "none"
    not_surviving_text = ", ".join(not_surviving) if not_surviving else "none"
    return (
        f"Bonferroni review: {comparison_count} comparisons were reported. "
        f"The Bonferroni-adjusted alpha threshold is {adjusted_alpha:.4f}. "
        f"Tests surviving correction: {surviving_text}. "
        f"Tests not surviving correction: {not_surviving_text}."
    )


def get_reviewer_agent(
    model: Model, model_settings: ModelSettings, retries: int = 2
) -> Agent[ReviewerDeps, ReviewerResult]:
    """Build a reviewer agent that vetoes hallucinated summaries."""
    system_prompt = """
You are a critical statistical reviewer. Given the AI-generated summary and the raw statistical outputs,
verify the narrative is faithful to the evidence. Reject hallucinations or unsupported claims.

Instructions:
1. Read the raw results and p-values. Only trust claims explicitly present in these inputs.
2. If the summary invents tests, misstates directionality, or ignores p-values/effect sizes, flag it.
3. Check that each performed test has a structured finding entry.
    If a finding is missing, add that test name to `missing_structure_flags`.
4. Check the structured raw-result metadata for missing effect sizes
    and missing confidence intervals where they are expected.
5. If more than one comparison is reported, add an informational Bonferroni multiplicity warning.
6. Missing structure, effect-size, confidence-interval, and multiplicity issues are FAIL-SOFT informational flags only.
     Do not set `approved` to false solely because those flags are present.
7. Produce an adjusted summary that is fully grounded in the provided evidence.
8. Set `approved` to false whenever you adjust the summary
    for a true evidence mismatch or when the evidence is otherwise insufficient.

Return EXACT JSON keys:
{
  "approved": <true|false>,
  "adjusted_summary": "<concise, evidence-grounded summary>",
  "hallucination_flags": ["<issue1>", "<issue2>"],
  "risk_score": <0.0-1.0 where 1.0 is high hallucination risk>,
    "notes": "<short rationale>",
    "missing_structure_flags": ["<test_name>"],
    "missing_effect_size_flags": ["<test_name>"],
    "missing_ci_flags": ["<test_name>"],
    "multiplicity_warning": "<informational warning or null>"
}
"""

    agent = Agent(
        model=model,
        model_settings=model_settings,
        deps_type=ReviewerDeps,
        end_strategy='early',
        output_type=ReviewerResult,
        name="Reviewer Agent",
        system_prompt=system_prompt,
        retries=retries,
    )

    @agent.tool
    def combined_inputs(ctx: RunContext[ReviewerDeps]) -> str:
        """Combine summary, raw results, and probabilities for inspection."""
        raw_messages = "\n".join(msg.content if isinstance(msg, AIMessage) else str(msg) for msg in ctx.deps.results)
        findings = json.dumps([finding.model_dump() for finding in ctx.deps.findings], default=str)
        result_context = json.dumps([evidence.model_dump() for evidence in ctx.deps.result_context], default=str)
        return (
            f"SUMMARY:\\n{ctx.deps.summary}\\n\\n"
            f"PERFORMED_TESTS:{ctx.deps.performed_tests}\n\n"
            f"FINDINGS:{findings}\n\n"
            f"RAW_RESULTS:\\n{raw_messages}\\n\\n"
            f"RESULT_CONTEXT:{result_context}\n\n"
            f"PROBABILITIES:{ctx.deps.probabilities}"
        )

    return agent
