# reviewer_agent.py

from langchain_core.messages import AIMessage
from pydantic import BaseModel, Field
from pydantic_ai import Agent, RunContext
from pydantic_ai.models.openai import Model, ModelSettings


class ReviewerDeps(BaseModel):
    """Inputs required by the reviewer agent."""

    summary: str = Field(description='Summary generated by the summariser node.')
    results: list[AIMessage] = Field(description='Raw AIMessage outputs from each statistical test.')
    probabilities: dict[str, float] = Field(description='P-values keyed by test name.')


class ReviewerResult(BaseModel):
    """Reviewer verdict with optional adjustments."""

    approved: bool = Field(description='True if the narrative matches the statistical evidence.')
    adjusted_summary: str = Field(description='Final vetted summary (may be same as input).')
    hallucination_flags: list[str] = Field(description='Specific issues or hallucinations detected.')
    risk_score: float = Field(description='0-1 confidence score; higher means higher risk of hallucination.')
    notes: str = Field(description='Supporting rationale or caveats.')

    def __str__(self) -> str:  # pragma: no cover - formatting helper
        status = 'APPROVED' if self.approved else 'FLAGGED'
        flags = '; '.join(self.hallucination_flags) if self.hallucination_flags else 'None'
        return (
            f'Reviewer Status: {status}\n'
            f'Adjusted Summary: {self.adjusted_summary}\n'
            f'Flags: {flags}\n'
            f'Risk Score: {self.risk_score:.2f}\n'
            f'Notes: {self.notes}'
        )


def get_reviewer_agent(
    model: Model, model_settings: ModelSettings, retries: int = 2
) -> Agent[ReviewerDeps, ReviewerResult]:
    """Build a reviewer agent that vetoes hallucinated summaries."""
    system_prompt = """
You are a critical statistical reviewer. Given the AI-generated summary and the raw statistical outputs,
verify the narrative is faithful to the evidence. Reject hallucinations or unsupported claims.

Instructions:
1. Read the raw results and p-values. Only trust claims explicitly present in these inputs.
2. If the summary invents tests, misstates directionality, or ignores p-values/effect sizes, flag it.
3. Produce an adjusted summary that is fully grounded in the provided evidence.
4. Set `approved` to false whenever you adjust or when evidence is insufficient.

Return EXACT JSON keys:
{
  "approved": <true|false>,
  "adjusted_summary": "<concise, evidence-grounded summary>",
  "hallucination_flags": ["<issue1>", "<issue2>"],
  "risk_score": <0.0-1.0 where 1.0 is high hallucination risk>,
  "notes": "<short rationale>"
}
"""

    agent = Agent(
        model=model,
        model_settings=model_settings,
        deps_type=ReviewerDeps,
        result_type=ReviewerResult,
        name='Reviewer Agent',
        system_prompt=system_prompt,
        retries=retries,
    )

    @agent.tool
    def combined_inputs(ctx: RunContext[ReviewerDeps]) -> str:
        """Combine summary, raw results, and probabilities for inspection."""
        raw_messages = '\n'.join(msg.content if isinstance(msg, AIMessage) else str(msg) for msg in ctx.deps.results)
        return (
            f'SUMMARY:\\n{ctx.deps.summary}\\n\\n'
            f'RAW_RESULTS:\\n{raw_messages}\\n\\n'
            f'PROBABILITIES:{ctx.deps.probabilities}'
        )

    return agent
